language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - MYSQL_VERSION=5.6
  - MYSQL_VERSION=5.7
  - MYSQL_VERSION=8.0

dist: trusty

sudo: required

services:
  - docker

before_install:
  - sudo /etc/init.d/mysql stop
  - make start_db V=$MYSQL_VERSION
  - make get_ip

install: composer install

script: vendor/bin/phpunit
